version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: clinica-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - clinica-net

  auth-service:
    build:
      context: ./servico-autenticacao
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinica?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"
    networks:
      - clinica-net

  paciente-service:
    build:
      context: ./servico-paciente
      dockerfile: Dockerfile
    container_name: paciente-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clinica?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"
    networks:
      - clinica-net

volumes:
  mysql_data:

networks:
  clinica-net:
    driver: bridge
